version: '3'

networks: 
  default:
    driver: bridge

services:
  account_manager:
    build: ./account_manager

  order_book:
    build: ./order_book

  sequencer:
    build: ./sequencer

  market_price:
    build: ./market_price

  db:
    container_name: roach
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.0.6}
    networks:
      - default
    command: start --logtostderr --insecure --locality=datacenter=dc-0
    ports:
      - 8000:8080
      - 9000:26257

  db-1:
    container_name: roach-1
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.0.6}
    networks:
      - default
    command: start --logtostderr --insecure --locality=datacenter=dc-0 --join=roach
    ports:
      - 8001:8080
      - 9001:26257

  # db-2:
  #   container_name: roach-2
  #   image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.0.6}
  #   networks:
  #     - default
  #   command: start --logtostderr --insecure --locality=datacenter=dc-0 --join=roach
  #   ports:
  #     - 8002:8080
  #     - 9002:26257
